using System;
using System.Reflection;
using System.Runtime.CompilerServices;
using UnityEngine;
[assembly: AssemblyVersion("0.0.0.0")]
[assembly: InternalsVisibleTo("Unity.PureCSharpTests")]
[assembly: InternalsVisibleTo("Unity.IntegrationTests")]
[assembly: InternalsVisibleTo("UnityEditor.Graphs")]
[assembly: InternalsVisibleTo("UnityEditor.WP8.Extensions")]
[assembly: InternalsVisibleTo("UnityEditor.Metro.Extensions")]
[assembly: InternalsVisibleTo("UnityEditor.iOS.Extensions")]
[assembly: InternalsVisibleTo("UnityEditor.Xbox360.Extensions")]
[assembly: InternalsVisibleTo("UnityEditor.BB10.Extensions")]
[assembly: InternalsVisibleTo("UnityEditor.Android.Extensions")]
[assembly: InternalsVisibleTo("UnityEditor.Tizen.Extensions")]
[assembly: InternalsVisibleTo("UnityEditor.PS3.Extensions")]
[assembly: InternalsVisibleTo("UnityEditor.SamsungTV.Extensions")]
[assembly: InternalsVisibleTo("UnityEditor.XboxOne.Extensions")]
[assembly: InternalsVisibleTo("UnityEditor.PSP2.Extensions")]
[assembly: InternalsVisibleTo("UnityEditor.PS4.Extensions")]
[assembly: InternalsVisibleTo("UnityEditor.PSM.Extensions")]
[assembly: RuntimeCompatibility(WrapNonExceptionThrows = true)]
[assembly: AssemblyIsEditorAssembly]
