using System;

namespace UnityEngine.Rendering
{
	public enum BuiltinShaderDefine
	{
		UNITY_NO_DXT5nm,
		UNITY_NO_RGBM,
		UNITY_USE_NATIVE_HDR,
		UNITY_ENABLE_REFLECTION_BUFFERS,
		UNITY_FRAMEBUFFER_FETCH_AVAILABLE,
		UNITY_ENABLE_NATIVE_SHADOW_LOOKUPS,
		UNITY_METAL_SHADOWS_USE_POINT_FILTERING,
		UNITY_NO_CUBEMAP_ARRAY,
		UNITY_NO_SCREENSPACE_SHADOWS,
		UNITY_USE_DITHER_MASK_FOR_ALPHABLENDED_SHADOWS,
		UNITY_PBS_USE_BRDF1,
		UNITY_PBS_USE_BRDF2,
		UNITY_PBS_USE_BRDF3,
		UNITY_NO_FULL_STANDARD_SHADER,
		UNITY_SPECCUBE_BOX_PROJECTION,
		UNITY_SPECCUBE_BLENDING,
		UNITY_ENABLE_DETAIL_NORMALMAP,
		SHADER_API_MOBILE,
		SHADER_API_DESKTOP,
		UNITY_HARDWARE_TIER1,
		UNITY_HARDWARE_TIER2,
		UNITY_HARDWARE_TIER3,
		UNITY_COLORSPACE_GAMMA
	}
}
